image: "debian"

variables:
    BYOND_MAJOR: "510"
    BYOND_MINOR: "1341"
    DM_MAPFILE1: "tgstation"

cache:
    key: "byond"
    paths:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

before_script:
    - dpkg --add-architecture i386
    - apt-get update
    - apt-get install --yes libc6-i386 libgcc1:i386 libstdc++6:i386 unzip make curl
    - chmod +x ./dm.sh
    - chmod +x ./install-byond.sh
    - ./install-byond.sh

tgstation:
    type: build
    script:
        - cat maps/*.* | awk '/step_x =/ && /step_y =/' | awk '!/step_y = 0/ || !/step_x = 0/ { exit 1 }'
        - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
        - ./dm.sh -M${DM_MAPFILE1} vgstation13.dme
    cache:
        key: "byond"
        paths:
        - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
